### ISSUE TITLE
Setup rec-cloud project

### ISSUE THREAD

**Issue by kenpusney** [rec-framework/rec-cloud#1]

**Comment by kenpusney** [comment]
```yaml
image: java:8
pipelines:
  default:
    - step:
        script:
          - bash ./gradlew build
        services:
          - postgres

definitions:
  services:
    postgres:
      image: postgres
```
